smtp:
  host: smtp.email.com
  username: myuser
  password: mypasswd
  sender: mysender

imap:
  host: imap.dest.com
  username: myuser2
  password: mypasswd2

mqtt:
  host: localhost
  topic_base: home/email_forwarding_checker

daemon:
  check_interval_hours: 5
  run_now: true

email_timeout: 300
delete_emails: true
emails: 
        - myfirstforwardaddress@greatdomain.com
        - myscondforwardaddress@superdomain.com
